// Generated by IconExtractorTest from androidx material-icons-extended.
// Faithful copies of the Rounded icons used by the shared composables,
// so they render on the CMP desktop target (extended icons are Android-only).
// Regenerate via :app:testDebugUnitTest --tests *IconExtractorTest.
package ee.schimke.meshcore.components.ui.icons

import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathNode
import androidx.compose.ui.unit.dp

/** Vendored Material Symbols (Rounded) — see MeshIcons.kt header. */
object MeshIcons {
  val Battery1Bar: ImageVector by lazy {
    ImageVector.Builder(
        name = "Rounded.Battery1Bar",
        defaultWidth = 24.0.dp,
        defaultHeight = 24.0.dp,
        viewportWidth = 24.0f,
        viewportHeight = 24.0f,
        autoMirror = false,
      )
      .apply {
        addPath(
          pathFillType = PathFillType.NonZero,
          pathData =
            listOf(
              PathNode.MoveTo(17.0f, 5.0f),
              PathNode.RelativeVerticalTo(16.0f),
              PathNode.RelativeCurveTo(0.0f, 0.55f, -0.45f, 1.0f, -1.0f, 1.0f),
              PathNode.HorizontalTo(8.0f),
              PathNode.RelativeCurveTo(-0.55f, 0.0f, -1.0f, -0.45f, -1.0f, -1.0f),
              PathNode.VerticalTo(5.0f),
              PathNode.RelativeCurveTo(0.0f, -0.55f, 0.45f, -1.0f, 1.0f, -1.0f),
              PathNode.RelativeHorizontalTo(2.0f),
              PathNode.VerticalTo(3.0f),
              PathNode.RelativeCurveTo(0.0f, -0.55f, 0.45f, -1.0f, 1.0f, -1.0f),
              PathNode.RelativeHorizontalTo(2.0f),
              PathNode.RelativeCurveTo(0.55f, 0.0f, 1.0f, 0.45f, 1.0f, 1.0f),
              PathNode.RelativeVerticalTo(1.0f),
              PathNode.RelativeHorizontalTo(2.0f),
              PathNode.CurveTo(16.55f, 4.0f, 17.0f, 4.45f, 17.0f, 5.0f),
              PathNode.Close,
              PathNode.MoveTo(15.0f, 6.0f),
              PathNode.HorizontalTo(9.0f),
              PathNode.RelativeVerticalTo(12.0f),
              PathNode.RelativeHorizontalTo(6.0f),
              PathNode.VerticalTo(6.0f),
              PathNode.Close,
            ),
        )
      }
      .build()
  }
  val Battery3Bar: ImageVector by lazy {
    ImageVector.Builder(
        name = "Rounded.Battery3Bar",
        defaultWidth = 24.0.dp,
        defaultHeight = 24.0.dp,
        viewportWidth = 24.0f,
        viewportHeight = 24.0f,
        autoMirror = false,
      )
      .apply {
        addPath(
          pathFillType = PathFillType.NonZero,
          pathData =
            listOf(
              PathNode.MoveTo(17.0f, 5.0f),
              PathNode.RelativeVerticalTo(16.0f),
              PathNode.RelativeCurveTo(0.0f, 0.55f, -0.45f, 1.0f, -1.0f, 1.0f),
              PathNode.HorizontalTo(8.0f),
              PathNode.RelativeCurveTo(-0.55f, 0.0f, -1.0f, -0.45f, -1.0f, -1.0f),
              PathNode.VerticalTo(5.0f),
              PathNode.RelativeCurveTo(0.0f, -0.55f, 0.45f, -1.0f, 1.0f, -1.0f),
              PathNode.RelativeHorizontalTo(2.0f),
              PathNode.VerticalTo(3.0f),
              PathNode.RelativeCurveTo(0.0f, -0.55f, 0.45f, -1.0f, 1.0f, -1.0f),
              PathNode.RelativeHorizontalTo(2.0f),
              PathNode.RelativeCurveTo(0.55f, 0.0f, 1.0f, 0.45f, 1.0f, 1.0f),
              PathNode.RelativeVerticalTo(1.0f),
              PathNode.RelativeHorizontalTo(2.0f),
              PathNode.CurveTo(16.55f, 4.0f, 17.0f, 4.45f, 17.0f, 5.0f),
              PathNode.Close,
              PathNode.MoveTo(15.0f, 6.0f),
              PathNode.HorizontalTo(9.0f),
              PathNode.RelativeVerticalTo(8.0f),
              PathNode.RelativeHorizontalTo(6.0f),
              PathNode.VerticalTo(6.0f),
              PathNode.Close,
            ),
        )
      }
      .build()
  }
  val Battery6Bar: ImageVector by lazy {
    ImageVector.Builder(
        name = "Rounded.Battery6Bar",
        defaultWidth = 24.0.dp,
        defaultHeight = 24.0.dp,
        viewportWidth = 24.0f,
        viewportHeight = 24.0f,
        autoMirror = false,
      )
      .apply {
        addPath(
          pathFillType = PathFillType.NonZero,
          pathData =
            listOf(
              PathNode.MoveTo(17.0f, 5.0f),
              PathNode.RelativeVerticalTo(16.0f),
              PathNode.RelativeCurveTo(0.0f, 0.55f, -0.45f, 1.0f, -1.0f, 1.0f),
              PathNode.HorizontalTo(8.0f),
              PathNode.RelativeCurveTo(-0.55f, 0.0f, -1.0f, -0.45f, -1.0f, -1.0f),
              PathNode.VerticalTo(5.0f),
              PathNode.RelativeCurveTo(0.0f, -0.55f, 0.45f, -1.0f, 1.0f, -1.0f),
              PathNode.RelativeHorizontalTo(2.0f),
              PathNode.VerticalTo(3.0f),
              PathNode.RelativeCurveTo(0.0f, -0.55f, 0.45f, -1.0f, 1.0f, -1.0f),
              PathNode.RelativeHorizontalTo(2.0f),
              PathNode.RelativeCurveTo(0.55f, 0.0f, 1.0f, 0.45f, 1.0f, 1.0f),
              PathNode.RelativeVerticalTo(1.0f),
              PathNode.RelativeHorizontalTo(2.0f),
              PathNode.CurveTo(16.55f, 4.0f, 17.0f, 4.45f, 17.0f, 5.0f),
              PathNode.Close,
              PathNode.MoveTo(15.0f, 6.0f),
              PathNode.HorizontalTo(9.0f),
              PathNode.RelativeVerticalTo(2.0f),
              PathNode.RelativeHorizontalTo(6.0f),
              PathNode.VerticalTo(6.0f),
              PathNode.Close,
            ),
        )
      }
      .build()
  }
  val BatteryFull: ImageVector by lazy {
    ImageVector.Builder(
        name = "Rounded.BatteryFull",
        defaultWidth = 24.0.dp,
        defaultHeight = 24.0.dp,
        viewportWidth = 24.0f,
        viewportHeight = 24.0f,
        autoMirror = false,
      )
      .apply {
        addPath(
          pathFillType = PathFillType.NonZero,
          pathData =
            listOf(
              PathNode.MoveTo(15.67f, 4.0f),
              PathNode.HorizontalTo(14.0f),
              PathNode.VerticalTo(3.0f),
              PathNode.RelativeCurveTo(0.0f, -0.55f, -0.45f, -1.0f, -1.0f, -1.0f),
              PathNode.RelativeHorizontalTo(-2.0f),
              PathNode.RelativeCurveTo(-0.55f, 0.0f, -1.0f, 0.45f, -1.0f, 1.0f),
              PathNode.RelativeVerticalTo(1.0f),
              PathNode.HorizontalTo(8.33f),
              PathNode.CurveTo(7.6f, 4.0f, 7.0f, 4.6f, 7.0f, 5.33f),
              PathNode.RelativeVerticalTo(15.33f),
              PathNode.CurveTo(7.0f, 21.4f, 7.6f, 22.0f, 8.34f, 22.0f),
              PathNode.RelativeHorizontalTo(7.32f),
              PathNode.RelativeCurveTo(0.74f, 0.0f, 1.34f, -0.6f, 1.34f, -1.33f),
              PathNode.VerticalTo(5.33f),
              PathNode.CurveTo(17.0f, 4.6f, 16.4f, 4.0f, 15.67f, 4.0f),
              PathNode.Close,
            ),
        )
      }
      .build()
  }
  val Close: ImageVector by lazy {
    ImageVector.Builder(
        name = "Rounded.Close",
        defaultWidth = 24.0.dp,
        defaultHeight = 24.0.dp,
        viewportWidth = 24.0f,
        viewportHeight = 24.0f,
        autoMirror = false,
      )
      .apply {
        addPath(
          pathFillType = PathFillType.NonZero,
          pathData =
            listOf(
              PathNode.MoveTo(18.3f, 5.71f),
              PathNode.RelativeCurveTo(-0.39f, -0.39f, -1.02f, -0.39f, -1.41f, 0.0f),
              PathNode.LineTo(12.0f, 10.59f),
              PathNode.LineTo(7.11f, 5.7f),
              PathNode.RelativeCurveTo(-0.39f, -0.39f, -1.02f, -0.39f, -1.41f, 0.0f),
              PathNode.RelativeCurveTo(-0.39f, 0.39f, -0.39f, 1.02f, 0.0f, 1.41f),
              PathNode.LineTo(10.59f, 12.0f),
              PathNode.LineTo(5.7f, 16.89f),
              PathNode.RelativeCurveTo(-0.39f, 0.39f, -0.39f, 1.02f, 0.0f, 1.41f),
              PathNode.RelativeCurveTo(0.39f, 0.39f, 1.02f, 0.39f, 1.41f, 0.0f),
              PathNode.LineTo(12.0f, 13.41f),
              PathNode.RelativeLineTo(4.89f, 4.89f),
              PathNode.RelativeCurveTo(0.39f, 0.39f, 1.02f, 0.39f, 1.41f, 0.0f),
              PathNode.RelativeCurveTo(0.39f, -0.39f, 0.39f, -1.02f, 0.0f, -1.41f),
              PathNode.LineTo(13.41f, 12.0f),
              PathNode.RelativeLineTo(4.89f, -4.89f),
              PathNode.RelativeCurveTo(0.38f, -0.38f, 0.38f, -1.02f, 0.0f, -1.4f),
              PathNode.Close,
            ),
        )
      }
      .build()
  }
  val Contrast: ImageVector by lazy {
    ImageVector.Builder(
        name = "Rounded.Contrast",
        defaultWidth = 24.0.dp,
        defaultHeight = 24.0.dp,
        viewportWidth = 24.0f,
        viewportHeight = 24.0f,
        autoMirror = false,
      )
      .apply {
        addPath(
          pathFillType = PathFillType.NonZero,
          pathData =
            listOf(
              PathNode.MoveTo(12.0f, 22.0f),
              PathNode.RelativeCurveTo(5.52f, 0.0f, 10.0f, -4.48f, 10.0f, -10.0f),
              PathNode.ReflectiveCurveTo(17.52f, 2.0f, 12.0f, 2.0f),
              PathNode.ReflectiveCurveTo(2.0f, 6.48f, 2.0f, 12.0f),
              PathNode.ReflectiveCurveTo(6.48f, 22.0f, 12.0f, 22.0f),
              PathNode.Close,
              PathNode.MoveTo(13.0f, 4.07f),
              PathNode.RelativeCurveTo(3.94f, 0.49f, 7.0f, 3.85f, 7.0f, 7.93f),
              PathNode.RelativeReflectiveCurveTo(-3.05f, 7.44f, -7.0f, 7.93f),
              PathNode.VerticalTo(4.07f),
              PathNode.Close,
            ),
        )
      }
      .build()
  }
  val ExpandLess: ImageVector by lazy {
    ImageVector.Builder(
        name = "Rounded.ExpandLess",
        defaultWidth = 24.0.dp,
        defaultHeight = 24.0.dp,
        viewportWidth = 24.0f,
        viewportHeight = 24.0f,
        autoMirror = false,
      )
      .apply {
        addPath(
          pathFillType = PathFillType.NonZero,
          pathData =
            listOf(
              PathNode.MoveTo(11.29f, 8.71f),
              PathNode.LineTo(6.7f, 13.3f),
              PathNode.RelativeCurveTo(-0.39f, 0.39f, -0.39f, 1.02f, 0.0f, 1.41f),
              PathNode.RelativeCurveTo(0.39f, 0.39f, 1.02f, 0.39f, 1.41f, 0.0f),
              PathNode.LineTo(12.0f, 10.83f),
              PathNode.RelativeLineTo(3.88f, 3.88f),
              PathNode.RelativeCurveTo(0.39f, 0.39f, 1.02f, 0.39f, 1.41f, 0.0f),
              PathNode.RelativeCurveTo(0.39f, -0.39f, 0.39f, -1.02f, 0.0f, -1.41f),
              PathNode.LineTo(12.7f, 8.71f),
              PathNode.RelativeCurveTo(-0.38f, -0.39f, -1.02f, -0.39f, -1.41f, 0.0f),
              PathNode.Close,
            ),
        )
      }
      .build()
  }
  val ExpandMore: ImageVector by lazy {
    ImageVector.Builder(
        name = "Rounded.ExpandMore",
        defaultWidth = 24.0.dp,
        defaultHeight = 24.0.dp,
        viewportWidth = 24.0f,
        viewportHeight = 24.0f,
        autoMirror = false,
      )
      .apply {
        addPath(
          pathFillType = PathFillType.NonZero,
          pathData =
            listOf(
              PathNode.MoveTo(15.88f, 9.29f),
              PathNode.LineTo(12.0f, 13.17f),
              PathNode.LineTo(8.12f, 9.29f),
              PathNode.RelativeCurveTo(-0.39f, -0.39f, -1.02f, -0.39f, -1.41f, 0.0f),
              PathNode.RelativeCurveTo(-0.39f, 0.39f, -0.39f, 1.02f, 0.0f, 1.41f),
              PathNode.RelativeLineTo(4.59f, 4.59f),
              PathNode.RelativeCurveTo(0.39f, 0.39f, 1.02f, 0.39f, 1.41f, 0.0f),
              PathNode.RelativeLineTo(4.59f, -4.59f),
              PathNode.RelativeCurveTo(0.39f, -0.39f, 0.39f, -1.02f, 0.0f, -1.41f),
              PathNode.RelativeCurveTo(-0.39f, -0.38f, -1.03f, -0.39f, -1.42f, 0.0f),
              PathNode.Close,
            ),
        )
      }
      .build()
  }
  val Fingerprint: ImageVector by lazy {
    ImageVector.Builder(
        name = "Rounded.Fingerprint",
        defaultWidth = 24.0.dp,
        defaultHeight = 24.0.dp,
        viewportWidth = 24.0f,
        viewportHeight = 24.0f,
        autoMirror = false,
      )
      .apply {
        addPath(
          pathFillType = PathFillType.NonZero,
          pathData =
            listOf(
              PathNode.MoveTo(17.81f, 4.47f),
              PathNode.RelativeCurveTo(-0.08f, 0.0f, -0.16f, -0.02f, -0.23f, -0.06f),
              PathNode.CurveTo(15.66f, 3.42f, 14.0f, 3.0f, 12.01f, 3.0f),
              PathNode.RelativeCurveTo(-1.98f, 0.0f, -3.86f, 0.47f, -5.57f, 1.41f),
              PathNode.RelativeCurveTo(-0.24f, 0.13f, -0.54f, 0.04f, -0.68f, -0.2f),
              PathNode.RelativeCurveTo(-0.13f, -0.24f, -0.04f, -0.55f, 0.2f, -0.68f),
              PathNode.CurveTo(7.82f, 2.52f, 9.86f, 2.0f, 12.01f, 2.0f),
              PathNode.RelativeCurveTo(2.13f, 0.0f, 3.99f, 0.47f, 6.03f, 1.52f),
              PathNode.RelativeCurveTo(0.25f, 0.13f, 0.34f, 0.43f, 0.21f, 0.67f),
              PathNode.RelativeCurveTo(-0.09f, 0.18f, -0.26f, 0.28f, -0.44f, 0.28f),
              PathNode.Close,
              PathNode.MoveTo(3.5f, 9.72f),
              PathNode.RelativeCurveTo(-0.1f, 0.0f, -0.2f, -0.03f, -0.29f, -0.09f),
              PathNode.RelativeCurveTo(-0.23f, -0.16f, -0.28f, -0.47f, -0.12f, -0.7f),
              PathNode.RelativeCurveTo(0.99f, -1.4f, 2.25f, -2.5f, 3.75f, -3.27f),
              PathNode.CurveTo(9.98f, 4.04f, 14.0f, 4.03f, 17.15f, 5.65f),
              PathNode.RelativeCurveTo(1.5f, 0.77f, 2.76f, 1.86f, 3.75f, 3.25f),
              PathNode.RelativeCurveTo(0.16f, 0.22f, 0.11f, 0.54f, -0.12f, 0.7f),
              PathNode.RelativeCurveTo(-0.23f, 0.16f, -0.54f, 0.11f, -0.7f, -0.12f),
              PathNode.RelativeCurveTo(-0.9f, -1.26f, -2.04f, -2.25f, -3.39f, -2.94f),
              PathNode.RelativeCurveTo(-2.87f, -1.47f, -6.54f, -1.47f, -9.4f, 0.01f),
              PathNode.RelativeCurveTo(-1.36f, 0.7f, -2.5f, 1.7f, -3.4f, 2.96f),
              PathNode.RelativeCurveTo(-0.08f, 0.14f, -0.23f, 0.21f, -0.39f, 0.21f),
              PathNode.Close,
              PathNode.MoveTo(9.75f, 21.79f),
              PathNode.RelativeCurveTo(-0.13f, 0.0f, -0.26f, -0.05f, -0.35f, -0.15f),
              PathNode.RelativeCurveTo(-0.87f, -0.87f, -1.34f, -1.43f, -2.01f, -2.64f),
              PathNode.RelativeCurveTo(-0.69f, -1.23f, -1.05f, -2.73f, -1.05f, -4.34f),
              PathNode.RelativeCurveTo(0.0f, -2.97f, 2.54f, -5.39f, 5.66f, -5.39f),
              PathNode.RelativeReflectiveCurveTo(5.66f, 2.42f, 5.66f, 5.39f),
              PathNode.RelativeCurveTo(0.0f, 0.28f, -0.22f, 0.5f, -0.5f, 0.5f),
              PathNode.RelativeReflectiveCurveTo(-0.5f, -0.22f, -0.5f, -0.5f),
              PathNode.RelativeCurveTo(0.0f, -2.42f, -2.09f, -4.39f, -4.66f, -4.39f),
              PathNode.RelativeReflectiveCurveTo(-4.66f, 1.97f, -4.66f, 4.39f),
              PathNode.RelativeCurveTo(0.0f, 1.44f, 0.32f, 2.77f, 0.93f, 3.85f),
              PathNode.RelativeCurveTo(0.64f, 1.15f, 1.08f, 1.64f, 1.85f, 2.42f),
              PathNode.RelativeCurveTo(0.19f, 0.2f, 0.19f, 0.51f, 0.0f, 0.71f),
              PathNode.RelativeCurveTo(-0.11f, 0.1f, -0.24f, 0.15f, -0.37f, 0.15f),
              PathNode.Close,
              PathNode.MoveTo(16.92f, 19.94f),
              PathNode.RelativeCurveTo(-1.19f, 0.0f, -2.24f, -0.3f, -3.1f, -0.89f),
              PathNode.RelativeCurveTo(-1.49f, -1.01f, -2.38f, -2.65f, -2.38f, -4.39f),
              PathNode.RelativeCurveTo(0.0f, -0.28f, 0.22f, -0.5f, 0.5f, -0.5f),
              PathNode.RelativeReflectiveCurveTo(0.5f, 0.22f, 0.5f, 0.5f),
              PathNode.RelativeCurveTo(0.0f, 1.41f, 0.72f, 2.74f, 1.94f, 3.56f),
              PathNode.RelativeCurveTo(0.71f, 0.48f, 1.54f, 0.71f, 2.54f, 0.71f),
              PathNode.RelativeCurveTo(0.24f, 0.0f, 0.64f, -0.03f, 1.04f, -0.1f),
              PathNode.RelativeCurveTo(0.27f, -0.05f, 0.53f, 0.13f, 0.58f, 0.41f),
              PathNode.RelativeCurveTo(0.05f, 0.27f, -0.13f, 0.53f, -0.41f, 0.58f),
              PathNode.RelativeCurveTo(-0.57f, 0.11f, -1.07f, 0.12f, -1.21f, 0.12f),
              PathNode.Close,
              PathNode.MoveTo(14.91f, 22.0f),
              PathNode.RelativeCurveTo(-0.04f, 0.0f, -0.09f, -0.01f, -0.13f, -0.02f),
              PathNode.RelativeCurveTo(-1.59f, -0.44f, -2.63f, -1.03f, -3.72f, -2.1f),
              PathNode.RelativeCurveTo(-1.4f, -1.39f, -2.17f, -3.24f, -2.17f, -5.22f),
              PathNode.RelativeCurveTo(0.0f, -1.62f, 1.38f, -2.94f, 3.08f, -2.94f),
              PathNode.RelativeReflectiveCurveTo(3.08f, 1.32f, 3.08f, 2.94f),
              PathNode.RelativeCurveTo(0.0f, 1.07f, 0.93f, 1.94f, 2.08f, 1.94f),
              PathNode.RelativeReflectiveCurveTo(2.08f, -0.87f, 2.08f, -1.94f),
              PathNode.RelativeCurveTo(0.0f, -3.77f, -3.25f, -6.83f, -7.25f, -6.83f),
              PathNode.RelativeCurveTo(-2.84f, 0.0f, -5.44f, 1.58f, -6.61f, 4.03f),
              PathNode.RelativeCurveTo(-0.39f, 0.81f, -0.59f, 1.76f, -0.59f, 2.8f),
              PathNode.RelativeCurveTo(0.0f, 0.78f, 0.07f, 2.01f, 0.67f, 3.61f),
              PathNode.RelativeCurveTo(0.1f, 0.26f, -0.03f, 0.55f, -0.29f, 0.64f),
              PathNode.RelativeCurveTo(-0.26f, 0.1f, -0.55f, -0.04f, -0.64f, -0.29f),
              PathNode.RelativeCurveTo(-0.49f, -1.31f, -0.73f, -2.61f, -0.73f, -3.96f),
              PathNode.RelativeCurveTo(0.0f, -1.2f, 0.23f, -2.29f, 0.68f, -3.24f),
              PathNode.RelativeCurveTo(1.33f, -2.79f, 4.28f, -4.6f, 7.51f, -4.6f),
              PathNode.RelativeCurveTo(4.55f, 0.0f, 8.25f, 3.51f, 8.25f, 7.83f),
              PathNode.RelativeCurveTo(0.0f, 1.62f, -1.38f, 2.94f, -3.08f, 2.94f),
              PathNode.RelativeReflectiveCurveTo(-3.08f, -1.32f, -3.08f, -2.94f),
              PathNode.RelativeCurveTo(0.0f, -1.07f, -0.93f, -1.94f, -2.08f, -1.94f),
              PathNode.RelativeReflectiveCurveTo(-2.08f, 0.87f, -2.08f, 1.94f),
              PathNode.RelativeCurveTo(0.0f, 1.71f, 0.66f, 3.31f, 1.87f, 4.51f),
              PathNode.RelativeCurveTo(0.95f, 0.94f, 1.86f, 1.46f, 3.27f, 1.85f),
              PathNode.RelativeCurveTo(0.27f, 0.07f, 0.42f, 0.35f, 0.35f, 0.61f),
              PathNode.RelativeCurveTo(-0.05f, 0.23f, -0.26f, 0.38f, -0.47f, 0.38f),
              PathNode.Close,
            ),
        )
      }
      .build()
  }
  val Groups: ImageVector by lazy {
    ImageVector.Builder(
        name = "Rounded.Groups",
        defaultWidth = 24.0.dp,
        defaultHeight = 24.0.dp,
        viewportWidth = 24.0f,
        viewportHeight = 24.0f,
        autoMirror = false,
      )
      .apply {
        addPath(
          pathFillType = PathFillType.NonZero,
          pathData =
            listOf(
              PathNode.MoveTo(12.0f, 12.75f),
              PathNode.RelativeCurveTo(1.63f, 0.0f, 3.07f, 0.39f, 4.24f, 0.9f),
              PathNode.RelativeCurveTo(1.08f, 0.48f, 1.76f, 1.56f, 1.76f, 2.73f),
              PathNode.LineTo(18.0f, 17.0f),
              PathNode.RelativeCurveTo(0.0f, 0.55f, -0.45f, 1.0f, -1.0f, 1.0f),
              PathNode.HorizontalTo(7.0f),
              PathNode.RelativeCurveTo(-0.55f, 0.0f, -1.0f, -0.45f, -1.0f, -1.0f),
              PathNode.RelativeLineTo(0.0f, -0.61f),
              PathNode.RelativeCurveTo(0.0f, -1.18f, 0.68f, -2.26f, 1.76f, -2.73f),
              PathNode.CurveTo(8.93f, 13.14f, 10.37f, 12.75f, 12.0f, 12.75f),
              PathNode.Close,
              PathNode.MoveTo(4.0f, 13.0f),
              PathNode.RelativeCurveTo(1.1f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f),
              PathNode.RelativeCurveTo(0.0f, -1.1f, -0.9f, -2.0f, -2.0f, -2.0f),
              PathNode.RelativeReflectiveCurveTo(-2.0f, 0.9f, -2.0f, 2.0f),
              PathNode.CurveTo(2.0f, 12.1f, 2.9f, 13.0f, 4.0f, 13.0f),
              PathNode.Close,
              PathNode.MoveTo(5.13f, 14.1f),
              PathNode.CurveTo(4.76f, 14.04f, 4.39f, 14.0f, 4.0f, 14.0f),
              PathNode.RelativeCurveTo(-0.99f, 0.0f, -1.93f, 0.21f, -2.78f, 0.58f),
              PathNode.CurveTo(0.48f, 14.9f, 0.0f, 15.62f, 0.0f, 16.43f),
              PathNode.LineTo(0.0f, 17.0f),
              PathNode.RelativeCurveTo(0.0f, 0.55f, 0.45f, 1.0f, 1.0f, 1.0f),
              PathNode.RelativeLineTo(3.5f, 0.0f),
              PathNode.RelativeVerticalTo(-1.61f),
              PathNode.CurveTo(4.5f, 15.56f, 4.73f, 14.78f, 5.13f, 14.1f),
              PathNode.Close,
              PathNode.MoveTo(20.0f, 13.0f),
              PathNode.RelativeCurveTo(1.1f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f),
              PathNode.RelativeCurveTo(0.0f, -1.1f, -0.9f, -2.0f, -2.0f, -2.0f),
              PathNode.RelativeReflectiveCurveTo(-2.0f, 0.9f, -2.0f, 2.0f),
              PathNode.CurveTo(18.0f, 12.1f, 18.9f, 13.0f, 20.0f, 13.0f),
              PathNode.Close,
              PathNode.MoveTo(24.0f, 16.43f),
              PathNode.RelativeCurveTo(0.0f, -0.81f, -0.48f, -1.53f, -1.22f, -1.85f),
              PathNode.CurveTo(21.93f, 14.21f, 20.99f, 14.0f, 20.0f, 14.0f),
              PathNode.RelativeCurveTo(-0.39f, 0.0f, -0.76f, 0.04f, -1.13f, 0.1f),
              PathNode.RelativeCurveTo(0.4f, 0.68f, 0.63f, 1.46f, 0.63f, 2.29f),
              PathNode.VerticalTo(18.0f),
              PathNode.RelativeLineTo(3.5f, 0.0f),
              PathNode.RelativeCurveTo(0.55f, 0.0f, 1.0f, -0.45f, 1.0f, -1.0f),
              PathNode.LineTo(24.0f, 16.43f),
              PathNode.Close,
              PathNode.MoveTo(12.0f, 6.0f),
              PathNode.RelativeCurveTo(1.66f, 0.0f, 3.0f, 1.34f, 3.0f, 3.0f),
              PathNode.RelativeCurveTo(0.0f, 1.66f, -1.34f, 3.0f, -3.0f, 3.0f),
              PathNode.RelativeReflectiveCurveTo(-3.0f, -1.34f, -3.0f, -3.0f),
              PathNode.CurveTo(9.0f, 7.34f, 10.34f, 6.0f, 12.0f, 6.0f),
              PathNode.Close,
            ),
        )
      }
      .build()
  }
  val Person: ImageVector by lazy {
    ImageVector.Builder(
        name = "Rounded.Person",
        defaultWidth = 24.0.dp,
        defaultHeight = 24.0.dp,
        viewportWidth = 24.0f,
        viewportHeight = 24.0f,
        autoMirror = false,
      )
      .apply {
        addPath(
          pathFillType = PathFillType.NonZero,
          pathData =
            listOf(
              PathNode.MoveTo(12.0f, 12.0f),
              PathNode.RelativeCurveTo(2.21f, 0.0f, 4.0f, -1.79f, 4.0f, -4.0f),
              PathNode.RelativeReflectiveCurveTo(-1.79f, -4.0f, -4.0f, -4.0f),
              PathNode.RelativeReflectiveCurveTo(-4.0f, 1.79f, -4.0f, 4.0f),
              PathNode.RelativeReflectiveCurveTo(1.79f, 4.0f, 4.0f, 4.0f),
              PathNode.Close,
              PathNode.MoveTo(12.0f, 14.0f),
              PathNode.RelativeCurveTo(-2.67f, 0.0f, -8.0f, 1.34f, -8.0f, 4.0f),
              PathNode.RelativeVerticalTo(1.0f),
              PathNode.RelativeCurveTo(0.0f, 0.55f, 0.45f, 1.0f, 1.0f, 1.0f),
              PathNode.RelativeHorizontalTo(14.0f),
              PathNode.RelativeCurveTo(0.55f, 0.0f, 1.0f, -0.45f, 1.0f, -1.0f),
              PathNode.RelativeVerticalTo(-1.0f),
              PathNode.RelativeCurveTo(0.0f, -2.66f, -5.33f, -4.0f, -8.0f, -4.0f),
              PathNode.Close,
            ),
        )
      }
      .build()
  }
  val Router: ImageVector by lazy {
    ImageVector.Builder(
        name = "Rounded.Router",
        defaultWidth = 24.0.dp,
        defaultHeight = 24.0.dp,
        viewportWidth = 24.0f,
        viewportHeight = 24.0f,
        autoMirror = false,
      )
      .apply {
        addPath(
          pathFillType = PathFillType.NonZero,
          pathData =
            listOf(
              PathNode.MoveTo(11.45f, 5.55f),
              PathNode.RelativeCurveTo(0.19f, 0.19f, 0.5f, 0.21f, 0.72f, 0.04f),
              PathNode.CurveTo(13.3f, 4.69f, 14.65f, 4.2f, 16.0f, 4.2f),
              PathNode.RelativeReflectiveCurveTo(2.7f, 0.49f, 3.84f, 1.39f),
              PathNode.RelativeCurveTo(0.21f, 0.17f, 0.52f, 0.15f, 0.72f, -0.04f),
              PathNode.RelativeLineTo(0.04f, -0.05f),
              PathNode.RelativeCurveTo(0.22f, -0.22f, 0.21f, -0.59f, -0.03f, -0.8f),
              PathNode.CurveTo(19.24f, 3.57f, 17.62f, 3.0f, 16.0f, 3.0f),
              PathNode.RelativeReflectiveCurveTo(-3.24f, 0.57f, -4.57f, 1.7f),
              PathNode.RelativeCurveTo(-0.24f, 0.21f, -0.26f, 0.57f, -0.03f, 0.8f),
              PathNode.RelativeLineTo(0.05f, 0.05f),
              PathNode.Close,
              PathNode.MoveTo(13.15f, 6.31f),
              PathNode.RelativeCurveTo(-0.25f, 0.2f, -0.26f, 0.58f, -0.04f, 0.8f),
              PathNode.RelativeLineTo(0.04f, 0.04f),
              PathNode.RelativeCurveTo(0.2f, 0.2f, 0.5f, 0.2f, 0.72f, 0.04f),
              PathNode.RelativeCurveTo(0.63f, -0.48f, 1.38f, -0.69f, 2.13f, -0.69f),
              PathNode.RelativeReflectiveCurveTo(1.5f, 0.21f, 2.13f, 0.68f),
              PathNode.RelativeCurveTo(0.22f, 0.17f, 0.53f, 0.16f, 0.72f, -0.04f),
              PathNode.RelativeLineTo(0.04f, -0.04f),
              PathNode.RelativeCurveTo(0.23f, -0.23f, 0.21f, -0.6f, -0.04f, -0.8f),
              PathNode.RelativeCurveTo(-0.83f, -0.64f, -1.84f, -1.0f, -2.85f, -1.0f),
              PathNode.RelativeReflectiveCurveTo(-2.02f, 0.36f, -2.85f, 1.01f),
              PathNode.Close,
              PathNode.MoveTo(19.0f, 13.0f),
              PathNode.RelativeHorizontalTo(-2.0f),
              PathNode.RelativeVerticalTo(-3.0f),
              PathNode.RelativeCurveTo(0.0f, -0.55f, -0.45f, -1.0f, -1.0f, -1.0f),
              PathNode.RelativeReflectiveCurveTo(-1.0f, 0.45f, -1.0f, 1.0f),
              PathNode.RelativeVerticalTo(3.0f),
              PathNode.LineTo(5.0f, 13.0f),
              PathNode.RelativeCurveTo(-1.1f, 0.0f, -2.0f, 0.9f, -2.0f, 2.0f),
              PathNode.RelativeVerticalTo(4.0f),
              PathNode.RelativeCurveTo(0.0f, 1.1f, 0.9f, 2.0f, 2.0f, 2.0f),
              PathNode.RelativeHorizontalTo(14.0f),
              PathNode.RelativeCurveTo(1.1f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f),
              PathNode.RelativeVerticalTo(-4.0f),
              PathNode.RelativeCurveTo(0.0f, -1.1f, -0.9f, -2.0f, -2.0f, -2.0f),
              PathNode.Close,
              PathNode.MoveTo(8.0f, 18.0f),
              PathNode.LineTo(6.0f, 18.0f),
              PathNode.RelativeVerticalTo(-2.0f),
              PathNode.RelativeHorizontalTo(2.0f),
              PathNode.RelativeVerticalTo(2.0f),
              PathNode.Close,
              PathNode.MoveTo(11.5f, 18.0f),
              PathNode.RelativeHorizontalTo(-2.0f),
              PathNode.RelativeVerticalTo(-2.0f),
              PathNode.RelativeHorizontalTo(2.0f),
              PathNode.RelativeVerticalTo(2.0f),
              PathNode.Close,
              PathNode.MoveTo(15.0f, 18.0f),
              PathNode.RelativeHorizontalTo(-2.0f),
              PathNode.RelativeVerticalTo(-2.0f),
              PathNode.RelativeHorizontalTo(2.0f),
              PathNode.RelativeVerticalTo(2.0f),
              PathNode.Close,
            ),
        )
      }
      .build()
  }
  val Sensors: ImageVector by lazy {
    ImageVector.Builder(
        name = "Rounded.Sensors",
        defaultWidth = 24.0.dp,
        defaultHeight = 24.0.dp,
        viewportWidth = 24.0f,
        viewportHeight = 24.0f,
        autoMirror = false,
      )
      .apply {
        addPath(
          pathFillType = PathFillType.NonZero,
          pathData =
            listOf(
              PathNode.MoveTo(8.54f, 8.54f),
              PathNode.RelativeCurveTo(0.35f, 0.35f, 0.37f, 0.88f, 0.1f, 1.29f),
              PathNode.CurveTo(8.24f, 10.45f, 8.0f, 11.2f, 8.0f, 12.0f),
              PathNode.RelativeCurveTo(0.0f, 0.8f, 0.24f, 1.55f, 0.64f, 2.17f),
              PathNode.RelativeCurveTo(0.27f, 0.41f, 0.24f, 0.95f, -0.11f, 1.29f),
              PathNode.RelativeCurveTo(-0.43f, 0.43f, -1.17f, 0.4f, -1.51f, -0.11f),
              PathNode.CurveTo(6.38f, 14.4f, 6.0f, 13.24f, 6.0f, 12.0f),
              PathNode.RelativeCurveTo(0.0f, -1.21f, 0.36f, -2.33f, 0.97f, -3.28f),
              PathNode.CurveTo(7.33f, 8.18f, 8.08f, 8.08f, 8.54f, 8.54f),
              PathNode.Close,
              PathNode.MoveTo(15.46f, 15.46f),
              PathNode.RelativeCurveTo(0.43f, 0.43f, 1.17f, 0.4f, 1.51f, -0.11f),
              PathNode.CurveTo(17.62f, 14.4f, 18.0f, 13.24f, 18.0f, 12.0f),
              PathNode.RelativeCurveTo(0.0f, -1.24f, -0.38f, -2.4f, -1.03f, -3.36f),
              PathNode.RelativeCurveTo(-0.34f, -0.5f, -1.08f, -0.54f, -1.51f, -0.11f),
              PathNode.RelativeCurveTo(-0.35f, 0.35f, -0.37f, 0.88f, -0.11f, 1.29f),
              PathNode.CurveTo(15.76f, 10.45f, 16.0f, 11.2f, 16.0f, 12.0f),
              PathNode.RelativeCurveTo(0.0f, 0.8f, -0.24f, 1.55f, -0.64f, 2.17f),
              PathNode.CurveTo(15.09f, 14.58f, 15.12f, 15.12f, 15.46f, 15.46f),
              PathNode.Close,
              PathNode.MoveTo(12.0f, 10.0f),
              PathNode.RelativeCurveTo(-1.1f, 0.0f, -2.0f, 0.9f, -2.0f, 2.0f),
              PathNode.RelativeReflectiveCurveTo(0.9f, 2.0f, 2.0f, 2.0f),
              PathNode.RelativeReflectiveCurveTo(2.0f, -0.9f, 2.0f, -2.0f),
              PathNode.ReflectiveCurveTo(13.1f, 10.0f, 12.0f, 10.0f),
              PathNode.Close,
              PathNode.MoveTo(18.32f, 18.32f),
              PathNode.RelativeCurveTo(0.42f, 0.42f, 1.12f, 0.39f, 1.5f, -0.08f),
              PathNode.CurveTo(21.18f, 16.53f, 22.0f, 14.36f, 22.0f, 12.0f),
              PathNode.RelativeReflectiveCurveTo(-0.82f, -4.53f, -2.18f, -6.24f),
              PathNode.RelativeCurveTo(-0.37f, -0.47f, -1.07f, -0.5f, -1.5f, -0.08f),
              PathNode.RelativeCurveTo(-0.36f, 0.36f, -0.4f, 0.92f, -0.08f, 1.32f),
              PathNode.RelativeCurveTo(1.1f, 1.37f, 1.76f, 3.11f, 1.76f, 5.0f),
              PathNode.RelativeReflectiveCurveTo(-0.66f, 3.63f, -1.76f, 5.0f),
              PathNode.CurveTo(17.92f, 17.39f, 17.96f, 17.96f, 18.32f, 18.32f),
              PathNode.Close,
              PathNode.MoveTo(5.68f, 5.68f),
              PathNode.RelativeCurveTo(-0.42f, -0.42f, -1.12f, -0.39f, -1.5f, 0.08f),
              PathNode.CurveTo(2.82f, 7.47f, 2.0f, 9.64f, 2.0f, 12.0f),
              PathNode.RelativeReflectiveCurveTo(0.82f, 4.53f, 2.18f, 6.24f),
              PathNode.RelativeCurveTo(0.37f, 0.47f, 1.07f, 0.5f, 1.5f, 0.08f),
              PathNode.RelativeCurveTo(0.36f, -0.36f, 0.4f, -0.92f, 0.08f, -1.32f),
              PathNode.CurveTo(4.66f, 15.63f, 4.0f, 13.89f, 4.0f, 12.0f),
              PathNode.RelativeReflectiveCurveTo(0.66f, -3.63f, 1.76f, -5.0f),
              PathNode.CurveTo(6.08f, 6.61f, 6.04f, 6.04f, 5.68f, 5.68f),
              PathNode.Close,
            ),
        )
      }
      .build()
  }
  val Settings: ImageVector by lazy {
    ImageVector.Builder(
        name = "Rounded.Settings",
        defaultWidth = 24.0.dp,
        defaultHeight = 24.0.dp,
        viewportWidth = 24.0f,
        viewportHeight = 24.0f,
        autoMirror = false,
      )
      .apply {
        addPath(
          pathFillType = PathFillType.NonZero,
          pathData =
            listOf(
              PathNode.MoveTo(19.5f, 12.0f),
              PathNode.RelativeCurveTo(0.0f, -0.23f, -0.01f, -0.45f, -0.03f, -0.68f),
              PathNode.RelativeLineTo(1.86f, -1.41f),
              PathNode.RelativeCurveTo(0.4f, -0.3f, 0.51f, -0.86f, 0.26f, -1.3f),
              PathNode.RelativeLineTo(-1.87f, -3.23f),
              PathNode.RelativeCurveTo(-0.25f, -0.44f, -0.79f, -0.62f, -1.25f, -0.42f),
              PathNode.RelativeLineTo(-2.15f, 0.91f),
              PathNode.RelativeCurveTo(-0.37f, -0.26f, -0.76f, -0.49f, -1.17f, -0.68f),
              PathNode.RelativeLineTo(-0.29f, -2.31f),
              PathNode.CurveTo(14.8f, 2.38f, 14.37f, 2.0f, 13.87f, 2.0f),
              PathNode.RelativeHorizontalTo(-3.73f),
              PathNode.CurveTo(9.63f, 2.0f, 9.2f, 2.38f, 9.14f, 2.88f),
              PathNode.LineTo(8.85f, 5.19f),
              PathNode.RelativeCurveTo(-0.41f, 0.19f, -0.8f, 0.42f, -1.17f, 0.68f),
              PathNode.LineTo(5.53f, 4.96f),
              PathNode.RelativeCurveTo(-0.46f, -0.2f, -1.0f, -0.02f, -1.25f, 0.42f),
              PathNode.LineTo(2.41f, 8.62f),
              PathNode.RelativeCurveTo(-0.25f, 0.44f, -0.14f, 0.99f, 0.26f, 1.3f),
              PathNode.RelativeLineTo(1.86f, 1.41f),
              PathNode.CurveTo(4.51f, 11.55f, 4.5f, 11.77f, 4.5f, 12.0f),
              PathNode.RelativeReflectiveCurveTo(0.01f, 0.45f, 0.03f, 0.68f),
              PathNode.RelativeLineTo(-1.86f, 1.41f),
              PathNode.RelativeCurveTo(-0.4f, 0.3f, -0.51f, 0.86f, -0.26f, 1.3f),
              PathNode.RelativeLineTo(1.87f, 3.23f),
              PathNode.RelativeCurveTo(0.25f, 0.44f, 0.79f, 0.62f, 1.25f, 0.42f),
              PathNode.RelativeLineTo(2.15f, -0.91f),
              PathNode.RelativeCurveTo(0.37f, 0.26f, 0.76f, 0.49f, 1.17f, 0.68f),
              PathNode.RelativeLineTo(0.29f, 2.31f),
              PathNode.CurveTo(9.2f, 21.62f, 9.63f, 22.0f, 10.13f, 22.0f),
              PathNode.RelativeHorizontalTo(3.73f),
              PathNode.RelativeCurveTo(0.5f, 0.0f, 0.93f, -0.38f, 0.99f, -0.88f),
              PathNode.RelativeLineTo(0.29f, -2.31f),
              PathNode.RelativeCurveTo(0.41f, -0.19f, 0.8f, -0.42f, 1.17f, -0.68f),
              PathNode.RelativeLineTo(2.15f, 0.91f),
              PathNode.RelativeCurveTo(0.46f, 0.2f, 1.0f, 0.02f, 1.25f, -0.42f),
              PathNode.RelativeLineTo(1.87f, -3.23f),
              PathNode.RelativeCurveTo(0.25f, -0.44f, 0.14f, -0.99f, -0.26f, -1.3f),
              PathNode.RelativeLineTo(-1.86f, -1.41f),
              PathNode.CurveTo(19.49f, 12.45f, 19.5f, 12.23f, 19.5f, 12.0f),
              PathNode.Close,
              PathNode.MoveTo(12.04f, 15.5f),
              PathNode.RelativeCurveTo(-1.93f, 0.0f, -3.5f, -1.57f, -3.5f, -3.5f),
              PathNode.RelativeReflectiveCurveTo(1.57f, -3.5f, 3.5f, -3.5f),
              PathNode.RelativeReflectiveCurveTo(3.5f, 1.57f, 3.5f, 3.5f),
              PathNode.ReflectiveCurveTo(13.97f, 15.5f, 12.04f, 15.5f),
              PathNode.Close,
            ),
        )
      }
      .build()
  }
  val Storage: ImageVector by lazy {
    ImageVector.Builder(
        name = "Rounded.Storage",
        defaultWidth = 24.0.dp,
        defaultHeight = 24.0.dp,
        viewportWidth = 24.0f,
        viewportHeight = 24.0f,
        autoMirror = false,
      )
      .apply {
        addPath(
          pathFillType = PathFillType.NonZero,
          pathData =
            listOf(
              PathNode.MoveTo(4.0f, 20.0f),
              PathNode.RelativeHorizontalTo(16.0f),
              PathNode.RelativeCurveTo(1.1f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f),
              PathNode.RelativeReflectiveCurveTo(-0.9f, -2.0f, -2.0f, -2.0f),
              PathNode.LineTo(4.0f, 16.0f),
              PathNode.RelativeCurveTo(-1.1f, 0.0f, -2.0f, 0.9f, -2.0f, 2.0f),
              PathNode.RelativeReflectiveCurveTo(0.9f, 2.0f, 2.0f, 2.0f),
              PathNode.Close,
              PathNode.MoveTo(4.0f, 17.0f),
              PathNode.RelativeHorizontalTo(2.0f),
              PathNode.RelativeVerticalTo(2.0f),
              PathNode.LineTo(4.0f, 19.0f),
              PathNode.RelativeVerticalTo(-2.0f),
              PathNode.Close,
              PathNode.MoveTo(2.0f, 6.0f),
              PathNode.RelativeCurveTo(0.0f, 1.1f, 0.9f, 2.0f, 2.0f, 2.0f),
              PathNode.RelativeHorizontalTo(16.0f),
              PathNode.RelativeCurveTo(1.1f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f),
              PathNode.RelativeReflectiveCurveTo(-0.9f, -2.0f, -2.0f, -2.0f),
              PathNode.LineTo(4.0f, 4.0f),
              PathNode.RelativeCurveTo(-1.1f, 0.0f, -2.0f, 0.9f, -2.0f, 2.0f),
              PathNode.Close,
              PathNode.MoveTo(6.0f, 7.0f),
              PathNode.LineTo(4.0f, 7.0f),
              PathNode.LineTo(4.0f, 5.0f),
              PathNode.RelativeHorizontalTo(2.0f),
              PathNode.RelativeVerticalTo(2.0f),
              PathNode.Close,
              PathNode.MoveTo(4.0f, 14.0f),
              PathNode.RelativeHorizontalTo(16.0f),
              PathNode.RelativeCurveTo(1.1f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f),
              PathNode.RelativeReflectiveCurveTo(-0.9f, -2.0f, -2.0f, -2.0f),
              PathNode.LineTo(4.0f, 10.0f),
              PathNode.RelativeCurveTo(-1.1f, 0.0f, -2.0f, 0.9f, -2.0f, 2.0f),
              PathNode.RelativeReflectiveCurveTo(0.9f, 2.0f, 2.0f, 2.0f),
              PathNode.Close,
              PathNode.MoveTo(4.0f, 11.0f),
              PathNode.RelativeHorizontalTo(2.0f),
              PathNode.RelativeVerticalTo(2.0f),
              PathNode.LineTo(4.0f, 13.0f),
              PathNode.RelativeVerticalTo(-2.0f),
              PathNode.Close,
            ),
        )
      }
      .build()
  }
  val Terminal: ImageVector by lazy {
    ImageVector.Builder(
        name = "Rounded.Terminal",
        defaultWidth = 24.0.dp,
        defaultHeight = 24.0.dp,
        viewportWidth = 24.0f,
        viewportHeight = 24.0f,
        autoMirror = false,
      )
      .apply {
        addPath(
          pathFillType = PathFillType.NonZero,
          pathData =
            listOf(
              PathNode.MoveTo(20.0f, 4.0f),
              PathNode.HorizontalTo(4.0f),
              PathNode.CurveTo(2.89f, 4.0f, 2.0f, 4.9f, 2.0f, 6.0f),
              PathNode.RelativeVerticalTo(12.0f),
              PathNode.RelativeCurveTo(0.0f, 1.1f, 0.89f, 2.0f, 2.0f, 2.0f),
              PathNode.RelativeHorizontalTo(16.0f),
              PathNode.RelativeCurveTo(1.1f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f),
              PathNode.VerticalTo(6.0f),
              PathNode.CurveTo(22.0f, 4.9f, 21.11f, 4.0f, 20.0f, 4.0f),
              PathNode.Close,
              PathNode.MoveTo(20.0f, 18.0f),
              PathNode.HorizontalTo(4.0f),
              PathNode.VerticalTo(8.0f),
              PathNode.RelativeHorizontalTo(16.0f),
              PathNode.VerticalTo(18.0f),
              PathNode.Close,
              PathNode.MoveTo(12.0f, 16.0f),
              PathNode.RelativeCurveTo(0.0f, -0.55f, 0.45f, -1.0f, 1.0f, -1.0f),
              PathNode.RelativeHorizontalTo(4.0f),
              PathNode.RelativeCurveTo(0.55f, 0.0f, 1.0f, 0.45f, 1.0f, 1.0f),
              PathNode.RelativeCurveTo(0.0f, 0.55f, -0.45f, 1.0f, -1.0f, 1.0f),
              PathNode.RelativeHorizontalTo(-4.0f),
              PathNode.CurveTo(12.45f, 17.0f, 12.0f, 16.55f, 12.0f, 16.0f),
              PathNode.Close,
              PathNode.MoveTo(6.79f, 9.71f),
              PathNode.RelativeCurveTo(0.39f, -0.39f, 1.02f, -0.39f, 1.41f, 0.0f),
              PathNode.RelativeLineTo(2.59f, 2.59f),
              PathNode.RelativeCurveTo(0.39f, 0.39f, 0.39f, 1.02f, 0.0f, 1.41f),
              PathNode.RelativeLineTo(-2.59f, 2.59f),
              PathNode.RelativeCurveTo(-0.39f, 0.39f, -1.02f, 0.39f, -1.41f, 0.0f),
              PathNode.RelativeCurveTo(-0.39f, -0.39f, -0.39f, -1.02f, 0.0f, -1.41f),
              PathNode.LineTo(8.67f, 13.0f),
              PathNode.RelativeLineTo(-1.88f, -1.88f),
              PathNode.CurveTo(6.4f, 10.73f, 6.4f, 10.1f, 6.79f, 9.71f),
              PathNode.Close,
            ),
        )
      }
      .build()
  }
  val WarningAmber: ImageVector by lazy {
    ImageVector.Builder(
        name = "Rounded.WarningAmber",
        defaultWidth = 24.0.dp,
        defaultHeight = 24.0.dp,
        viewportWidth = 24.0f,
        viewportHeight = 24.0f,
        autoMirror = false,
      )
      .apply {
        addPath(
          pathFillType = PathFillType.NonZero,
          pathData =
            listOf(
              PathNode.MoveTo(12.0f, 5.99f),
              PathNode.LineTo(19.53f, 19.0f),
              PathNode.LineTo(4.47f, 19.0f),
              PathNode.LineTo(12.0f, 5.99f),
              PathNode.MoveTo(2.74f, 18.0f),
              PathNode.RelativeCurveTo(-0.77f, 1.33f, 0.19f, 3.0f, 1.73f, 3.0f),
              PathNode.RelativeHorizontalTo(15.06f),
              PathNode.RelativeCurveTo(1.54f, 0.0f, 2.5f, -1.67f, 1.73f, -3.0f),
              PathNode.LineTo(13.73f, 4.99f),
              PathNode.RelativeCurveTo(-0.77f, -1.33f, -2.69f, -1.33f, -3.46f, 0.0f),
              PathNode.LineTo(2.74f, 18.0f),
              PathNode.Close,
              PathNode.MoveTo(11.0f, 11.0f),
              PathNode.RelativeVerticalTo(2.0f),
              PathNode.RelativeCurveTo(0.0f, 0.55f, 0.45f, 1.0f, 1.0f, 1.0f),
              PathNode.RelativeReflectiveCurveTo(1.0f, -0.45f, 1.0f, -1.0f),
              PathNode.RelativeVerticalTo(-2.0f),
              PathNode.RelativeCurveTo(0.0f, -0.55f, -0.45f, -1.0f, -1.0f, -1.0f),
              PathNode.RelativeReflectiveCurveTo(-1.0f, 0.45f, -1.0f, 1.0f),
              PathNode.Close,
              PathNode.MoveTo(11.0f, 16.0f),
              PathNode.RelativeHorizontalTo(2.0f),
              PathNode.RelativeVerticalTo(2.0f),
              PathNode.RelativeHorizontalTo(-2.0f),
              PathNode.Close,
            ),
        )
      }
      .build()
  }
  val Wifi: ImageVector by lazy {
    ImageVector.Builder(
        name = "Rounded.Wifi",
        defaultWidth = 24.0.dp,
        defaultHeight = 24.0.dp,
        viewportWidth = 24.0f,
        viewportHeight = 24.0f,
        autoMirror = false,
      )
      .apply {
        addPath(
          pathFillType = PathFillType.NonZero,
          pathData =
            listOf(
              PathNode.MoveTo(2.06f, 10.06f),
              PathNode.RelativeCurveTo(0.51f, 0.51f, 1.32f, 0.56f, 1.87f, 0.1f),
              PathNode.RelativeCurveTo(4.67f, -3.84f, 11.45f, -3.84f, 16.13f, -0.01f),
              PathNode.RelativeCurveTo(0.56f, 0.46f, 1.38f, 0.42f, 1.89f, -0.09f),
              PathNode.RelativeCurveTo(0.59f, -0.59f, 0.55f, -1.57f, -0.1f, -2.1f),
              PathNode.RelativeCurveTo(-5.71f, -4.67f, -13.97f, -4.67f, -19.69f, 0.0f),
              PathNode.RelativeCurveTo(-0.65f, 0.52f, -0.7f, 1.5f, -0.1f, 2.1f),
              PathNode.Close,
              PathNode.MoveTo(9.82f, 17.82f),
              PathNode.RelativeLineTo(1.47f, 1.47f),
              PathNode.RelativeCurveTo(0.39f, 0.39f, 1.02f, 0.39f, 1.41f, 0.0f),
              PathNode.RelativeLineTo(1.47f, -1.47f),
              PathNode.RelativeCurveTo(0.47f, -0.47f, 0.37f, -1.28f, -0.23f, -1.59f),
              PathNode.RelativeCurveTo(-1.22f, -0.63f, -2.68f, -0.63f, -3.91f, 0.0f),
              PathNode.RelativeCurveTo(-0.57f, 0.31f, -0.68f, 1.12f, -0.21f, 1.59f),
              PathNode.Close,
              PathNode.MoveTo(6.09f, 14.09f),
              PathNode.RelativeCurveTo(0.49f, 0.49f, 1.26f, 0.54f, 1.83f, 0.13f),
              PathNode.RelativeCurveTo(2.44f, -1.73f, 5.72f, -1.73f, 8.16f, 0.0f),
              PathNode.RelativeCurveTo(0.57f, 0.4f, 1.34f, 0.36f, 1.83f, -0.13f),
              PathNode.RelativeLineTo(0.01f, -0.01f),
              PathNode.RelativeCurveTo(0.6f, -0.6f, 0.56f, -1.62f, -0.13f, -2.11f),
              PathNode.RelativeCurveTo(-3.44f, -2.49f, -8.13f, -2.49f, -11.58f, 0.0f),
              PathNode.RelativeCurveTo(-0.69f, 0.5f, -0.73f, 1.51f, -0.12f, 2.12f),
              PathNode.Close,
            ),
        )
      }
      .build()
  }
  val Logout: ImageVector by lazy {
    ImageVector.Builder(
        name = "AutoMirrored.Rounded.Logout",
        defaultWidth = 24.0.dp,
        defaultHeight = 24.0.dp,
        viewportWidth = 24.0f,
        viewportHeight = 24.0f,
        autoMirror = true,
      )
      .apply {
        addPath(
          pathFillType = PathFillType.NonZero,
          pathData =
            listOf(
              PathNode.MoveTo(5.0f, 5.0f),
              PathNode.RelativeHorizontalTo(6.0f),
              PathNode.RelativeCurveTo(0.55f, 0.0f, 1.0f, -0.45f, 1.0f, -1.0f),
              PathNode.RelativeVerticalTo(0.0f),
              PathNode.RelativeCurveTo(0.0f, -0.55f, -0.45f, -1.0f, -1.0f, -1.0f),
              PathNode.HorizontalTo(5.0f),
              PathNode.CurveTo(3.9f, 3.0f, 3.0f, 3.9f, 3.0f, 5.0f),
              PathNode.RelativeVerticalTo(14.0f),
              PathNode.RelativeCurveTo(0.0f, 1.1f, 0.9f, 2.0f, 2.0f, 2.0f),
              PathNode.RelativeHorizontalTo(6.0f),
              PathNode.RelativeCurveTo(0.55f, 0.0f, 1.0f, -0.45f, 1.0f, -1.0f),
              PathNode.RelativeVerticalTo(0.0f),
              PathNode.RelativeCurveTo(0.0f, -0.55f, -0.45f, -1.0f, -1.0f, -1.0f),
              PathNode.HorizontalTo(5.0f),
              PathNode.VerticalTo(5.0f),
              PathNode.Close,
            ),
        )
        addPath(
          pathFillType = PathFillType.NonZero,
          pathData =
            listOf(
              PathNode.MoveTo(20.65f, 11.65f),
              PathNode.RelativeLineTo(-2.79f, -2.79f),
              PathNode.CurveTo(17.54f, 8.54f, 17.0f, 8.76f, 17.0f, 9.21f),
              PathNode.VerticalTo(11.0f),
              PathNode.RelativeHorizontalTo(-7.0f),
              PathNode.RelativeCurveTo(-0.55f, 0.0f, -1.0f, 0.45f, -1.0f, 1.0f),
              PathNode.RelativeVerticalTo(0.0f),
              PathNode.RelativeCurveTo(0.0f, 0.55f, 0.45f, 1.0f, 1.0f, 1.0f),
              PathNode.RelativeHorizontalTo(7.0f),
              PathNode.RelativeVerticalTo(1.79f),
              PathNode.RelativeCurveTo(0.0f, 0.45f, 0.54f, 0.67f, 0.85f, 0.35f),
              PathNode.RelativeLineTo(2.79f, -2.79f),
              PathNode.CurveTo(20.84f, 12.16f, 20.84f, 11.84f, 20.65f, 11.65f),
              PathNode.Close,
            ),
        )
      }
      .build()
  }
  val Message: ImageVector by lazy {
    ImageVector.Builder(
        name = "AutoMirrored.Rounded.Message",
        defaultWidth = 24.0.dp,
        defaultHeight = 24.0.dp,
        viewportWidth = 24.0f,
        viewportHeight = 24.0f,
        autoMirror = true,
      )
      .apply {
        addPath(
          pathFillType = PathFillType.NonZero,
          pathData =
            listOf(
              PathNode.MoveTo(20.0f, 2.0f),
              PathNode.LineTo(4.0f, 2.0f),
              PathNode.RelativeCurveTo(-1.1f, 0.0f, -1.99f, 0.9f, -1.99f, 2.0f),
              PathNode.LineTo(2.0f, 22.0f),
              PathNode.RelativeLineTo(4.0f, -4.0f),
              PathNode.RelativeHorizontalTo(14.0f),
              PathNode.RelativeCurveTo(1.1f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f),
              PathNode.LineTo(22.0f, 4.0f),
              PathNode.RelativeCurveTo(0.0f, -1.1f, -0.9f, -2.0f, -2.0f, -2.0f),
              PathNode.Close,
              PathNode.MoveTo(17.0f, 14.0f),
              PathNode.LineTo(7.0f, 14.0f),
              PathNode.RelativeCurveTo(-0.55f, 0.0f, -1.0f, -0.45f, -1.0f, -1.0f),
              PathNode.RelativeReflectiveCurveTo(0.45f, -1.0f, 1.0f, -1.0f),
              PathNode.RelativeHorizontalTo(10.0f),
              PathNode.RelativeCurveTo(0.55f, 0.0f, 1.0f, 0.45f, 1.0f, 1.0f),
              PathNode.RelativeReflectiveCurveTo(-0.45f, 1.0f, -1.0f, 1.0f),
              PathNode.Close,
              PathNode.MoveTo(17.0f, 11.0f),
              PathNode.LineTo(7.0f, 11.0f),
              PathNode.RelativeCurveTo(-0.55f, 0.0f, -1.0f, -0.45f, -1.0f, -1.0f),
              PathNode.RelativeReflectiveCurveTo(0.45f, -1.0f, 1.0f, -1.0f),
              PathNode.RelativeHorizontalTo(10.0f),
              PathNode.RelativeCurveTo(0.55f, 0.0f, 1.0f, 0.45f, 1.0f, 1.0f),
              PathNode.RelativeReflectiveCurveTo(-0.45f, 1.0f, -1.0f, 1.0f),
              PathNode.Close,
              PathNode.MoveTo(17.0f, 8.0f),
              PathNode.LineTo(7.0f, 8.0f),
              PathNode.RelativeCurveTo(-0.55f, 0.0f, -1.0f, -0.45f, -1.0f, -1.0f),
              PathNode.RelativeReflectiveCurveTo(0.45f, -1.0f, 1.0f, -1.0f),
              PathNode.RelativeHorizontalTo(10.0f),
              PathNode.RelativeCurveTo(0.55f, 0.0f, 1.0f, 0.45f, 1.0f, 1.0f),
              PathNode.RelativeReflectiveCurveTo(-0.45f, 1.0f, -1.0f, 1.0f),
              PathNode.Close,
            ),
        )
      }
      .build()
  }
}
