package ee.schimke.meshcore.app.icontool

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.rounded.Logout
import androidx.compose.material.icons.automirrored.rounded.Message
import androidx.compose.material.icons.rounded.Battery1Bar
import androidx.compose.material.icons.rounded.Battery3Bar
import androidx.compose.material.icons.rounded.Battery6Bar
import androidx.compose.material.icons.rounded.BatteryFull
import androidx.compose.material.icons.rounded.Close
import androidx.compose.material.icons.rounded.Contrast
import androidx.compose.material.icons.rounded.ExpandLess
import androidx.compose.material.icons.rounded.ExpandMore
import androidx.compose.material.icons.rounded.Fingerprint
import androidx.compose.material.icons.rounded.Groups
import androidx.compose.material.icons.rounded.Person
import androidx.compose.material.icons.rounded.Router
import androidx.compose.material.icons.rounded.Sensors
import androidx.compose.material.icons.rounded.Settings
import androidx.compose.material.icons.rounded.Storage
import androidx.compose.material.icons.rounded.Terminal
import androidx.compose.material.icons.rounded.WarningAmber
import androidx.compose.material.icons.rounded.Wifi
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathNode
import androidx.compose.ui.graphics.vector.VectorGroup
import androidx.compose.ui.graphics.vector.VectorPath
import java.io.File
import org.junit.Test

/**
 * One-shot generator: serializes the Material `*-icons-extended` ImageVectors we
 * use (Android-only on CMP) into a commonMain Kotlin file of equivalent
 * ImageVectors, so the shared composables can render off-Android. Run with
 * `./gradlew :app:testDebugUnitTest --tests *IconExtractorTest`.
 */
class IconExtractorTest {
    private val icons: Map<String, ImageVector> = linkedMapOf(
        "Battery1Bar" to Icons.Rounded.Battery1Bar,
        "Battery3Bar" to Icons.Rounded.Battery3Bar,
        "Battery6Bar" to Icons.Rounded.Battery6Bar,
        "BatteryFull" to Icons.Rounded.BatteryFull,
        "Close" to Icons.Rounded.Close,
        "Contrast" to Icons.Rounded.Contrast,
        "ExpandLess" to Icons.Rounded.ExpandLess,
        "ExpandMore" to Icons.Rounded.ExpandMore,
        "Fingerprint" to Icons.Rounded.Fingerprint,
        "Groups" to Icons.Rounded.Groups,
        "Person" to Icons.Rounded.Person,
        "Router" to Icons.Rounded.Router,
        "Sensors" to Icons.Rounded.Sensors,
        "Settings" to Icons.Rounded.Settings,
        "Storage" to Icons.Rounded.Storage,
        "Terminal" to Icons.Rounded.Terminal,
        "WarningAmber" to Icons.Rounded.WarningAmber,
        "Wifi" to Icons.Rounded.Wifi,
        "Logout" to Icons.AutoMirrored.Rounded.Logout,
        "Message" to Icons.AutoMirrored.Rounded.Message,
    )

    @Test
    fun generate() {
        val sb = StringBuilder()
        sb.appendLine("// Generated by IconExtractorTest from androidx material-icons-extended.")
        sb.appendLine("// Faithful copies of the Rounded icons used by the shared composables,")
        sb.appendLine("// so they render on the CMP desktop target (extended icons are Android-only).")
        sb.appendLine("// Regenerate via :app:testDebugUnitTest --tests *IconExtractorTest.")
        sb.appendLine("package ee.schimke.meshcore.components.ui.icons")
        sb.appendLine()
        sb.appendLine("import androidx.compose.ui.graphics.PathFillType")
        sb.appendLine("import androidx.compose.ui.graphics.vector.ImageVector")
        sb.appendLine("import androidx.compose.ui.graphics.vector.PathNode")
        sb.appendLine("import androidx.compose.ui.unit.dp")
        sb.appendLine()
        sb.appendLine("/** Vendored Material Symbols (Rounded) — see MeshIcons.kt header. */")
        sb.appendLine("object MeshIcons {")
        for ((name, iv) in icons) {
            sb.appendLine(renderIcon(name, iv))
        }
        sb.appendLine("}")

        val out = File(
            "../meshcore-components/src/commonMain/kotlin/" +
                "ee/schimke/meshcore/components/ui/icons/MeshIcons.kt",
        )
        out.parentFile.mkdirs()
        out.writeText(sb.toString())
        println("WROTE ${out.absolutePath} (${out.length()} bytes, ${icons.size} icons)")
    }

    private fun renderIcon(name: String, iv: ImageVector): String {
        val paths = mutableListOf<VectorPath>()
        collectPaths(iv.root, paths)
        val b = StringBuilder()
        b.appendLine("    val $name: ImageVector by lazy {")
        b.appendLine("        ImageVector.Builder(")
        b.appendLine("            name = ${quote(iv.name)},")
        b.appendLine("            defaultWidth = ${iv.defaultWidth.value}.dp,")
        b.appendLine("            defaultHeight = ${iv.defaultHeight.value}.dp,")
        b.appendLine("            viewportWidth = ${iv.viewportWidth}f,")
        b.appendLine("            viewportHeight = ${iv.viewportHeight}f,")
        b.appendLine("            autoMirror = ${iv.autoMirror},")
        b.appendLine("        ).apply {")
        for (p in paths) {
            b.appendLine("            addPath(")
            b.appendLine("                pathFillType = PathFillType.${fillType(p)},")
            b.appendLine("                pathData = listOf(")
            for (node in p.pathData) {
                b.appendLine("                    ${renderNode(node)},")
            }
            b.appendLine("                ),")
            b.appendLine("            )")
        }
        b.appendLine("        }.build()")
        b.append("    }")
        return b.toString()
    }

    private fun collectPaths(group: VectorGroup, into: MutableList<VectorPath>) {
        for (node in group) {
            when (node) {
                is VectorPath -> into.add(node)
                is VectorGroup -> collectPaths(node, into)
            }
        }
    }

    private fun fillType(p: VectorPath): String =
        if (p.pathFillType.toString().contains("EvenOdd", ignoreCase = true)) "EvenOdd" else "NonZero"

    private fun f(v: Float): String = "${v}f"

    private fun renderNode(n: PathNode): String = when (n) {
        is PathNode.Close -> "PathNode.Close"
        is PathNode.MoveTo -> "PathNode.MoveTo(${f(n.x)}, ${f(n.y)})"
        is PathNode.RelativeMoveTo -> "PathNode.RelativeMoveTo(${f(n.dx)}, ${f(n.dy)})"
        is PathNode.LineTo -> "PathNode.LineTo(${f(n.x)}, ${f(n.y)})"
        is PathNode.RelativeLineTo -> "PathNode.RelativeLineTo(${f(n.dx)}, ${f(n.dy)})"
        is PathNode.HorizontalTo -> "PathNode.HorizontalTo(${f(n.x)})"
        is PathNode.RelativeHorizontalTo -> "PathNode.RelativeHorizontalTo(${f(n.dx)})"
        is PathNode.VerticalTo -> "PathNode.VerticalTo(${f(n.y)})"
        is PathNode.RelativeVerticalTo -> "PathNode.RelativeVerticalTo(${f(n.dy)})"
        is PathNode.CurveTo ->
            "PathNode.CurveTo(${f(n.x1)}, ${f(n.y1)}, ${f(n.x2)}, ${f(n.y2)}, ${f(n.x3)}, ${f(n.y3)})"
        is PathNode.RelativeCurveTo ->
            "PathNode.RelativeCurveTo(${f(n.dx1)}, ${f(n.dy1)}, ${f(n.dx2)}, ${f(n.dy2)}, ${f(n.dx3)}, ${f(n.dy3)})"
        is PathNode.ReflectiveCurveTo ->
            "PathNode.ReflectiveCurveTo(${f(n.x1)}, ${f(n.y1)}, ${f(n.x2)}, ${f(n.y2)})"
        is PathNode.RelativeReflectiveCurveTo ->
            "PathNode.RelativeReflectiveCurveTo(${f(n.dx1)}, ${f(n.dy1)}, ${f(n.dx2)}, ${f(n.dy2)})"
        is PathNode.QuadTo ->
            "PathNode.QuadTo(${f(n.x1)}, ${f(n.y1)}, ${f(n.x2)}, ${f(n.y2)})"
        is PathNode.RelativeQuadTo ->
            "PathNode.RelativeQuadTo(${f(n.dx1)}, ${f(n.dy1)}, ${f(n.dx2)}, ${f(n.dy2)})"
        is PathNode.ReflectiveQuadTo -> "PathNode.ReflectiveQuadTo(${f(n.x)}, ${f(n.y)})"
        is PathNode.RelativeReflectiveQuadTo -> "PathNode.RelativeReflectiveQuadTo(${f(n.dx)}, ${f(n.dy)})"
        is PathNode.ArcTo ->
            "PathNode.ArcTo(${f(n.horizontalEllipseRadius)}, ${f(n.verticalEllipseRadius)}, " +
                "${f(n.theta)}, ${n.isMoreThanHalf}, ${n.isPositiveArc}, ${f(n.arcStartX)}, ${f(n.arcStartY)})"
        is PathNode.RelativeArcTo ->
            "PathNode.RelativeArcTo(${f(n.horizontalEllipseRadius)}, ${f(n.verticalEllipseRadius)}, " +
                "${f(n.theta)}, ${n.isMoreThanHalf}, ${n.isPositiveArc}, ${f(n.arcStartDx)}, ${f(n.arcStartDy)})"
    }

    private fun quote(s: String) = "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
}
