package ee.schimke.meshcore.app.ui.theme

import androidx.activity.ComponentActivity
import androidx.activity.SystemBarStyle
import androidx.activity.compose.LocalActivity
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Typography
import ee.schimke.meshcore.components.ui.theme.MeshcoreBrandedTypography
import ee.schimke.meshcore.components.ui.theme.MeshcoreDarkColors
import ee.schimke.meshcore.components.ui.theme.MeshcoreLightColors
import ee.schimke.meshcore.components.ui.theme.MeshcoreShapes
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.platform.LocalContext
import android.graphics.Color as AndroidColor

// ---------------------------------------------------------------------------
// MeshCore Material 3 theme.
//
// Seed: teal #00695C (reads as "signal / radio / network"). Palette was
// generated by hand from standard M3 tonal rules — primary is tone 40
// light / tone 80 dark; tertiary is a complementary amber used for
// warnings (low battery, weak signal). See STYLEGUIDE.md for usage
// guidance. This file is the single source of truth for colors, shapes
// and typography in the app.
// ---------------------------------------------------------------------------

// Typography is split into two Typography instances:
//   - MeshcoreBrandedTypography (Orbitron/Space Grotesk/JetBrains Mono)
//     used when the user picks the Meshcore palette. Defined in
//     MeshcoreFonts.kt alongside the font declarations.
//   - A plain M3-default Typography used when the user picks the
//     Dynamic palette, so Material You's system look isn't disrupted
//     by our custom display faces.
private val DefaultTypography: Typography = Typography()

/** True while a theme-catalog provider already owns the preview's outer theme. */
internal val LocalThemeCatalogOverride = staticCompositionLocalOf { false }

/**
 * Top-level theme wrapper. All previews and the MainActivity content
 * should be wrapped in this — never in a bare MaterialTheme {} — so
 * the design is applied consistently.
 *
 * [darkTheme] / [palette] are low-level switches; prefer the
 * [ThemeSettings] overload in application code so the user's persisted
 * preferences are honored.
 */
@Composable
fun MeshcoreTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    palette: ThemePalette = ThemePalette.Meshcore,
    content: @Composable () -> Unit,
) {
    // Theme catalog providers wrap the preview function. Most MeshCore previews also install their
    // normal default theme in their body; without this guard that inner theme would shadow the
    // selected provider and every theme override would render identical pixels.
    if (LocalThemeCatalogOverride.current) {
        content()
        return
    }

    val useDynamic = palette == ThemePalette.Dynamic
    val scheme = when {
        useDynamic && darkTheme -> dynamicDarkColorScheme(LocalContext.current)
        useDynamic && !darkTheme -> dynamicLightColorScheme(LocalContext.current)
        darkTheme -> MeshcoreDarkColors
        else -> MeshcoreLightColors
    }
    val typography = when (palette) {
        ThemePalette.Meshcore -> MeshcoreBrandedTypography
        ThemePalette.Dynamic -> DefaultTypography
    }
    // Keep system bar icons legible regardless of the user's chosen theme:
    // enableEdgeToEdge in MainActivity only samples the system setting once,
    // so re-apply it here against the app's effective darkTheme.
    val activity = LocalActivity.current as? ComponentActivity
    if (activity != null) {
        DisposableEffect(activity, darkTheme) {
            activity.enableEdgeToEdge(
                statusBarStyle = SystemBarStyle.auto(
                    AndroidColor.TRANSPARENT,
                    AndroidColor.TRANSPARENT,
                ) { darkTheme },
                navigationBarStyle = SystemBarStyle.auto(
                    AndroidColor.WHITE,
                    AndroidColor.BLACK,
                ) { darkTheme },
            )
            onDispose {}
        }
    }
    MaterialTheme(
        colorScheme = scheme,
        typography = typography,
        shapes = MeshcoreShapes,
        content = content,
    )
}

/** Resolve a [ThemeMode] against the current system dark setting. */
@Composable
fun MeshcoreTheme(
    mode: ThemeMode,
    palette: ThemePalette = ThemePalette.Meshcore,
    content: @Composable () -> Unit,
) {
    val dark = when (mode) {
        ThemeMode.System -> isSystemInDarkTheme()
        ThemeMode.Light -> false
        ThemeMode.Dark -> true
    }
    MeshcoreTheme(darkTheme = dark, palette = palette, content = content)
}

@Composable
fun MeshcoreTheme(
    settings: ThemeSettings,
    content: @Composable () -> Unit,
) {
    MeshcoreTheme(mode = settings.mode, palette = settings.palette, content = content)
}
